### ISSUE TITLE
No tira ni patras

### ISSUE THREAD

**Issue by OlaiGarnelo** [Sauleteh/genshin-impact-simulador-artefactos#1]
No tira las librerias, espero que lo fixeen rapido.
![image](https://github.com/Sauleteh/genshin-impact-simulador-artefactos/assets/50480993/e1e7c551-ccc8-40b9-96d1-f84cf8c9e2f3)

**Comment by UO279176** [comment]
> No tira las librerias, espero que lo fixeen rapido. ![image](https://user-images.githubusercontent.com/50480993/268666944-e1e7c551-ccc8-40b9-96d1-f84cf8c9e2f3.png)

Si no instalas Microsoft Visual C++ Redistributables no funcionará, creo. Ni siquiera juegas al Genshin, so feo.
